### ISSUE TITLE
Windows Server 2016 compatibility

### ISSUE THREAD

**Issue by felixmschilling** [ErikEJ/SqlCeCmd#3]
Dear Sir,

I really appreciate your hard work. The software helps me a lot. I just wanted to migrate from windows server 2008 to 2016. Unfortunately I can't start the software anymore. Is this maybe a known bug?

**Comment by ErikEJ** [comment]
Please share the error message.

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if you can provide more info?
