### ISSUE TITLE
(Exception from HRESULT: 0x8007007E - Misunderstood use, perhaps?

### ISSUE THREAD

**Issue by dichaelen** [ErikEJ/SqlCeCmd#4]
Hi again,

Now I am playing around with your command line tool, to ultimately implement it in my Python script, but perhaps I am missing something?

Based on your example I simply start with basics of a full query from one of the data base tables:
sqlcecmd -d "Data Source=Db.sdf" -q "select * from BsmResult"
But I get this (at first):

Inner Exception: System.DllNotFoundException: Unable to load DLL 'sqlceme35.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlServerCe.NativeMethods.GetSqlCeVersionInfo(IntPtr& pwszVersion)
   at System.Data.SqlServerCe.NativeMethods.LoadValidLibrary(String modulePath, Int32 moduleVersion)
   at System.Data.SqlServerCe.NativeMethods.LoadNativeBinaries()

Then I can naturally locate the *.dll and try to run everything from the same location, but then I get:

Error: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at System.Data.SqlServerCe.NativeMethods.DllAddRef()
   at SqlCeCmd.SqlCeCommandHelper..ctor(String connectionString)
   at SqlCeCmd.Program.Main(String[] args)

I have installed this:
https://www.microsoft.com/en-us/download/details.aspx?id=1639
and this:
https://www.microsoft.com/en-us/download/details.aspx?id=5783

What am I missing here? Is it just to late for me to look at this!?

**Comment by ErikEJ** [comment]
Hmm.. I should update to .NET 4.0! 
I have just tested locally, and it works fine - have you followed in SQL runtime install instructions? **On a 64-bit Computer, install both the 32-bit and the 64-bit version of the SQL Server Compact 3.5 SP2 MSI files.**

**Comment by ErikEJ** [comment]
Re the: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. 

You obviously copied the wrong set o DLLs - but that is not recommended. Install the runtimes (x86 and x64) properly instead.

**Comment by ErikEJ** [comment]
I have logged: https://github.com/ErikEJ/SqlCeCmd/issues/5

**Comment by dichaelen** [comment]
Thank you so much! No I forgot to install the 64-bit version. I also find it very late in the instruction - especially after 11 pm :-)

I will close this - thanks (again) for an impressive fast response!
