### ISSUE TITLE
Destination .tmp file is not created

### ISSUE THREAD

**Issue by katalin2003** [ErikEJ/SqlCeCmd#6]
Hello,
I used the `-e repairrecover` and `-e repairdelete` flag in order to repair a corrupted `name.sdf` file.
A `name.log` file is created in which a Destination path to a sqlXXXX.tmp is given but sadly, this file is never created.

The log file reads this:

> Header checksum is valid.
> Source      : C:\temp\name.sdf
> Destination : C:\Users\xyz\AppData\Local\Temp\sqlE233.tmp
> Repairing - verMajor: 4, verMinor: 0, verBuild: 8482, verPoint: 1
> Time - 2021-07-04 18:00:42.477
> 
>  All Pages have valid checksum.
> Parse the db file and build list of tables ... DONE.
> Page with valid ordinal not found - idPage: 1, iPage: 10773
> Cleanup Page list ... DONE.
> Scan bad pages ... DONE.
> Parse SysObjects table ... DONE.
> Copy Schema ... DONE.
> Copy Tables ... DONE.
> Copy Constraints ... DONE.
> Copy Indexes ... DONE.
> Copy Constraints ... DONE.

Any idea on what I'm missing?
Thank you.

**Comment by ErikEJ** [comment]
Virus scanner?

File is so corrupted it cannot be repaired?

Update to very latest runtime?

**Comment by katalin2003** [comment]
Thank you for the very prompt answer, @ErikEJ.
1. No anti-virus, Defender disabled as well (Windows 10 x64 VM).
2. Maybe
3. Have the latest

Was I wrong in thinking that the generated .tmp file was supposed to be the repaired database and that the original one would remain untouched?
I just noticed that the source `name.sdf` shrank in size, ~30% and I could open it. Which leads me to believe that SqlCeCmd alters the input .sdf?

**Comment by ErikEJ** [comment]
I think the engine always can alter an open database file.

>> Was I wrong in thinking that the generated .tmp file was supposed to be the repaired database and that the original one would remain untouched?

Yes, I think so.

**Comment by ErikEJ** [comment]
Yes, it is in-place: https://github.com/ErikEJ/SqlCeCmd/blob/master/src/SqlCeHelper/SqlCeEngineHelper.cs#L81

https://docs.microsoft.com/en-us/previous-versions/sql/compact/sql-server-compact-4.0/h093xwk1(v=vs.100)

**Comment by katalin2003** [comment]
Got it, thank you for the confirmation.
While the database I was given lost so much data after the recovery that it's unusable, I want to thank you so much for this tool, regardless. Who knows, it might come in handy in the future.
